tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "libpq"
brew "libtiff"
brew "little-cms2"
brew "python@3.7"
brew "python@3.9", link: false
brew "ta-lib"
brew "webp"
brew "yarn"
brew "heroku/brew/heroku"
